
-- RUN SCHEMA BEFORE SERVER SETUP
CREATE SCHEMA IF NOT EXISTS `citydb`;



-- CHAR SET NEEDS THE BE ALTERED TO ALLOW CURRENCY SYMBOLS
use citydb;
ALTER TABLE cities CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;